### PR TITLE
Typo error on 2-webhook-signature-validation.md

### PR DESCRIPTION
**Pull request by oostanc**
Is only a typo error from " to ' on `crypto     = re quire("crypto');`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My change follows the documentation style of this project.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by justinedelson** [comment]
@oostanc thank you for submitting this. Do you plan to sign the CLA?

**Comment by oostanc** [comment]
@justinedelson I've followed the procedure and signed some weeks ago. I'll try one more time today.

**Comment by oostanc** [comment]
CLA Signed

**Comment by justinedelson** [comment]
@adobe/open-source-office can you help identify why cla-bot is still failing for this PR?

**Comment by macdonst** [comment]
@oostanc I see that you have signed the CLA a couple of times but none of the signed documents have `oostanc` as one of the github user id's. Can you sign it one more time, you won't need to add everyone, just sign it yourself.

**Comment by justinedelson** [comment]
Thanks for your help @macdonst and @oostanc for submitting this patch. Appreciate the hard work to get a single character changed :)

**Comment by oostanc** [comment]
You can lose a lot of time only for a single wrong character :)

**Pull request merged**
