### PR TITLE
rolling out aio-theme@4.9.7

### PR DESCRIPTION
**Pull request by dmitrymatio**
## Description

Current state: **errors during new link checker and linter tests**

This PR is part of the DevSite team's effort to roll out a major release aio-them@4.9.0 across all the AdobeDocs repos.

Release Notes - Feature Highlights:
- Search Enhancements
- Link Checker
- Local Linter enhancements
- Easing of dependabot PR notifications
- Mobile Nav improvements
- Github Issues template enhancement

Additionally in this PR:
- Reindexed all content for search

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dmitrymatio** [comment]
@bohnertchris There are some errors brought up by the new link checker and linter during build. Are you able to review and fix those?

**Comment by bohnertchris** [comment]
Hello @dmitrymatio 

I am not sure what you mean by the linter. In the latest checks I can't find any references to problems with it. 

With regard to the the checks marked **Latest Pull Request / validate (pull_request)**, as far as I can tell there are no errors being thrown by the link checker, only warnings.

https://github.com/AdobeDocs/cloudmanager-api-docs/actions/runs/4757414189/jobs/8454204187?pr=239

With regard to the checks marked **CI Build / build (pull_request)**, there is little data, but it looks like GitHub thinks you are somehow using an old `.github/workflows/ci.yml` file that has `ubuntu-18.04` whereas the current version of the file uses `ubuntu-latest`.

https://github.com/AdobeDocs/cloudmanager-api-docs/actions/runs/4757414187/jobs/8454204213?pr=239

I hope this is helpful. I am not familiar with the inner workings of this tool and am rather just a user.

**Comment by dmitrymatio** [comment]
@bohnertchris I've updated the CI file and the test is passing now.

Regarding the warnings in the Latest Pull Request workflow: the warnings are non blocking but they indicate links that don't resolve due to missing files or wrong paths. This is a new test workflow we introduced to assist with fixing 404s across the site. If possible please check if they can be fixed asap.

on a separate note, I'm struggling to index the `src/pages/reference/api.md` file due to some permission denial when the redoc-cli commands are invoked. Would you happen to know what could've caused it? due to the non standard nature of this repo I'm struggling to figure out what would do it as this doesn't happen in our templated repos even the really custom ones 😅 my current workaround is to comment out the `openAPISpec` during indexing but that means there won't be any results for the actual content of the commented file.

Aside from that I think we're good to merge this PR

**Comment by bohnertchris** [comment]
It is interesting to know that the PR recognizes warnings as an error/failure. However I am also not sure why any of these warnings are generated.

`src/pages/guides/api-usage/index.md` lists six pages as not existing. However the published page has no broken links. https://developer.adobe.com/experience-cloud/cloud-manager/guides/

`src/pages/guides/getting-started/index.md` also lists six pages as not existing. However the published page has no broken links. https://developer.adobe.com/experience-cloud/cloud-manager/guides/

`src/pages/guides/getting-started/understanding-the-api.md` lists two pages as not existing. However the publisher page has no broken links. https://developer.adobe.com/experience-cloud/cloud-manager/guides/getting-started/understanding-the-api

`src/pages/index.md` lists seven unknown pages but the published page has no broken links. https://developer.adobe.com/experience-cloud/cloud-manager/

`src/pages/reference/index.md` lists two unknown pages but the published page has no broken links. https://developer.adobe.com/experience-cloud/cloud-manager/reference/

I am sorry, but with regard to your question about the "permission denial when the redoc-cli commands are invoked," as I mentioned previously, I am not the owner of this repo, nor the maintainer. I only use it to publish API documentation and I have no insight into how it is set up or how it works. I regret that I have no insight to offer here.

**Comment by dmitrymatio** [comment]
@bohnertchris Based on your comment, I realized the issue with the links is the formatting. 
Although they resolved in the application, the links didn't match the supported formats. See docs here: https://github.com/adobe/aio-theme#internal-links .

I applied reformats and have resolved the link checker complaints however I noticed that some of those links were imported on pages where the relative link format would break. The solution was to use absolute formats for those. Could you help me confirm that those links work on stage https://developer-stage.adobe.com/experience-cloud/cloud-manager/ .

Regarding the permission denial errors, could you tag whoever is more familiar with the setup of this repo? From my conversation with the ADP team this was a custom effort from the experience cloud team we just don't remember who handled this setup.

If all is well on stage please go ahead and merge this PR in. Thank you.

**Comment by bohnertchris** [comment]
Thank you for looking into the link warnings, @dmitrymatio. It mostly looks good on the staging instance, but the links on this page https://developer-stage.adobe.com/experience-cloud/cloud-manager/guides/ under the *API Usage* heading do not work. They resolve, but the pages are empty of content. Not sure if this is a problem with the staging instance or an actual issue.

I wish I could provide you with more information on this repository. But once again, I was introduced to this repository as a user in order to author content and publish it. I do not know who set it up or who is more knowledgeable of its inner working. Justin Edelson introduced me to this platform some time ago.

**Comment by dmitrymatio** [comment]
@bohnertchris could you take another look at https://developer-stage.adobe.com/experience-cloud/cloud-manager/guides/ should be fixed now

**Comment by bohnertchris** [comment]
Yes, @dmitrymatio, the links are working as expected now. However it looks like the checks have now flagged another linting error.

**Comment by dmitrymatio** [comment]
@bohnertchris Glad to hear that. Sounds like we're good to merge and deploy then. The linting errors are rather simple and to do with content. They're non blocking but if you'd like to match the expected formatting of the linter it will make things more consistent. It wasn't able to run before because the link checker would error and stop the tests before the linter (so it's not new issues). Can I leave it up to you to fix the linting errors or not (optional)? I would like to complete the upgrade asap 😅

**Review by bohnertchris — APPROVED** [review]
I appreciate trying to get more eyes on change before committing to `main`, but I lack the technical knowledge to comment on any technical changes.

**Comment by bohnertchris** [comment]
Changes are complete, @dmitrymatio. Should I merge or does this need to be coordinated somehow with other changes that you are making with regard to the upgrade?

**Pull request merged**
